### ISSUE TITLE
rpiplay missing

### ISSUE THREAD

**Issue by Botspot** [CleanMachine1/RPi-Stuff#1]
```
Installing RPi-Play with install-32 script
--2021-04-28 15:24:45--  https://raw.githubusercontent.com/CleanMachine1/RPi-Stuff/main/debfiles/rpiplay.deb
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-04-28 15:24:45 ERROR 404: Not Found.

Failed to download .deb file

Failed to install RPi-Play with install-32 script!
```

**Comment by CleanMachine1** [comment]
Yes, sorry about that I took it down and kept it just for personal use since I thought you would use a different one, let me compile it again and make one

**Comment by CleanMachine1** [comment]
I'll name it the same thing as well

**Comment by Botspot** [comment]
> I'll name it the same thing as well

While you're at it, could you add that zenity script and menu button stuff to your deb file?

**Comment by CleanMachine1** [comment]
There will be some troubleshooting as the scripts need to link and I didn't know the directory to be using so you will have to fill and fix some gaps/errors

I am currently having some difficulties compiling with checkinstall due to a segmentation fault relating to the raspberry pi checkinstall so I will need some time.
I will probably have everything done within 24 hours

**Comment by Botspot** [comment]
> There will be some troubleshooting as the scripts need to link and I didn't know the directory to be using so you will have to fill and fix some gaps/errors

That's fine. We can go back and forth until everything's working well.

**Comment by CleanMachine1** [comment]
I can't get rpiplay to compile using checkinstall, however it compiles fine without, just use the twisterOS one that chukymilk has in his repo

That makes it easier

Sorry I am lazy and can't be bothered to troubleshoot

**Comment by CleanMachine1** [comment]
Visit the PR for everything
